site_name: Salt AI Documentation

nav:
  - Getting Started: index.md
  - Platform Resources: resources.md

theme:
  name: material

  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - tables

  #codeblocks
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets

  #callouts
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  #definition lists
  - def_list

  #table of content
  - toc:
      permalink: true

  - pymdownx.keys

  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/get-salt-AI
      name: Salt AI Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fT2G63zn
      name: Salt AI Discord