site_name: Salt AI Documentation
nav:
  - Getting Started: index.md
  - Platform Resources: resources.md
  - Nodes packs documentation:
      - Comfy:
          - BasicScheduler: md/Comfy/BasicScheduler.md
          - CLIPLoader: md/Comfy/CLIPLoader.md
          - CLIPMergeSimple: md/Comfy/CLIPMergeSimple.md
          - CLIPSave: md/Comfy/CLIPSave.md
          - CLIPSetLastLayer: md/Comfy/CLIPSetLastLayer.md
          - CLIPTextEncode: md/Comfy/CLIPTextEncode.md
          - CLIPTextEncodeControlnet: md/Comfy/CLIPTextEncodeControlnet.md
          - CLIPTextEncodeSDXL: md/Comfy/CLIPTextEncodeSDXL.md
          - CLIPTextEncodeSDXLRefiner: md/Comfy/CLIPTextEncodeSDXLRefiner.md
          - CLIPVisionEncode: md/Comfy/CLIPVisionEncode.md
          - CLIPVisionLoader: md/Comfy/CLIPVisionLoader.md
          - Canny: md/Comfy/Canny.md
          - CheckpointLoader: md/Comfy/CheckpointLoader.md
          - CheckpointLoaderSimple: md/Comfy/CheckpointLoaderSimple.md
          - CheckpointSave: md/Comfy/CheckpointSave.md
          - ConditioningAverage: md/Comfy/ConditioningAverage.md
          - ConditioningCombine: md/Comfy/ConditioningCombine.md
          - ConditioningConcat: md/Comfy/ConditioningConcat.md
          - ConditioningSetArea: md/Comfy/ConditioningSetArea.md
          - ConditioningSetAreaPercentage: md/Comfy/ConditioningSetAreaPercentage.md
          - ConditioningSetAreaStrength: md/Comfy/ConditioningSetAreaStrength.md
          - ConditioningSetMask: md/Comfy/ConditioningSetMask.md
          - ConditioningSetTimestepRange: md/Comfy/ConditioningSetTimestepRange.md
          - ConditioningZeroOut: md/Comfy/ConditioningZeroOut.md
          - ControlNetApply: md/Comfy/ControlNetApply.md
          - ControlNetApplyAdvanced: md/Comfy/ControlNetApplyAdvanced.md
          - ControlNetLoader: md/Comfy/ControlNetLoader.md
          - CropMask: md/Comfy/CropMask.md
          - DiffControlNetLoader: md/Comfy/DiffControlNetLoader.md
          - DiffusersLoader: md/Comfy/DiffusersLoader.md
          - DualCLIPLoader: md/Comfy/DualCLIPLoader.md
          - EmptyImage: md/Comfy/EmptyImage.md
          - EmptyLatentImage: md/Comfy/EmptyLatentImage.md
          - ExponentialScheduler: md/Comfy/ExponentialScheduler.md
          - FeatherMask: md/Comfy/FeatherMask.md
          - FlipSigmas: md/Comfy/FlipSigmas.md
          - FreeU: md/Comfy/FreeU.md
          - FreeU_V2: md/Comfy/FreeU_V2.md
          - GLIGENLoader: md/Comfy/GLIGENLoader.md
          - GLIGENTextBoxApply: md/Comfy/GLIGENTextBoxApply.md
          - GrowMask: md/Comfy/GrowMask.md
          - HyperTile: md/Comfy/HyperTile.md
          - HypernetworkLoader: md/Comfy/HypernetworkLoader.md
          - ImageBatch: md/Comfy/ImageBatch.md
          - ImageBlend: md/Comfy/ImageBlend.md
          - ImageBlur: md/Comfy/ImageBlur.md
          - ImageColorToMask: md/Comfy/ImageColorToMask.md
          - ImageCompositeMasked: md/Comfy/ImageCompositeMasked.md
          - ImageCrop: md/Comfy/ImageCrop.md
          - ImageFromBatch: md/Comfy/ImageFromBatch.md
          - ImageInvert: md/Comfy/ImageInvert.md
          - ImageOnlyCheckpointLoader: md/Comfy/ImageOnlyCheckpointLoader.md
          - ImageOnlyCheckpointSave: md/Comfy/ImageOnlyCheckpointSave.md
          - ImagePadForOutpaint: md/Comfy/ImagePadForOutpaint.md
          - ImageQuantize: md/Comfy/ImageQuantize.md
          - ImageScale: md/Comfy/ImageScale.md
          - ImageScaleBy: md/Comfy/ImageScaleBy.md
          - ImageScaleToTotalPixels: md/Comfy/ImageScaleToTotalPixels.md
          - ImageSharpen: md/Comfy/ImageSharpen.md
          - ImageToMask: md/Comfy/ImageToMask.md
          - ImageUpscaleWithModel: md/Comfy/ImageUpscaleWithModel.md
          - InpaintModelConditioning: md/Comfy/InpaintModelConditioning.md
          - InvertMask: md/Comfy/InvertMask.md
          - JoinImageWithAlpha: md/Comfy/JoinImageWithAlpha.md
          - KSampler: md/Comfy/KSampler.md
          - KSamplerAdvanced: md/Comfy/KSamplerAdvanced.md
          - KSamplerSelect: md/Comfy/KSamplerSelect.md
          - KarrasScheduler: md/Comfy/KarrasScheduler.md
          - LatentAdd: md/Comfy/LatentAdd.md
          - LatentBatch: md/Comfy/LatentBatch.md
          - LatentBatchSeedBehavior: md/Comfy/LatentBatchSeedBehavior.md
          - LatentBlend: md/Comfy/LatentBlend.md
          - LatentComposite: md/Comfy/LatentComposite.md
          - LatentCompositeMasked: md/Comfy/LatentCompositeMasked.md
          - LatentCrop: md/Comfy/LatentCrop.md
          - LatentFlip: md/Comfy/LatentFlip.md
          - LatentFromBatch: md/Comfy/LatentFromBatch.md
          - LatentInterpolate: md/Comfy/LatentInterpolate.md
          - LatentMultiply: md/Comfy/LatentMultiply.md
          - LatentRotate: md/Comfy/LatentRotate.md
          - LatentSubtract: md/Comfy/LatentSubtract.md
          - LatentUpscale: md/Comfy/LatentUpscale.md
          - LatentUpscaleBy: md/Comfy/LatentUpscaleBy.md
          - LoadImage: md/Comfy/LoadImage.md
          - LoadImageMask: md/Comfy/LoadImageMask.md
          - LoadLatent: md/Comfy/LoadLatent.md
          - LoraLoader: md/Comfy/LoraLoader.md
          - LoraLoaderModelOnly: md/Comfy/LoraLoaderModelOnly.md
          - MaskComposite: md/Comfy/MaskComposite.md
          - MaskToImage: md/Comfy/MaskToImage.md
          - ModelMergeAdd: md/Comfy/ModelMergeAdd.md
          - ModelMergeBlocks: md/Comfy/ModelMergeBlocks.md
          - ModelMergeSimple: md/Comfy/ModelMergeSimple.md
          - ModelMergeSubtract: md/Comfy/ModelMergeSubtract.md
          - ModelSamplingContinuousEDM: md/Comfy/ModelSamplingContinuousEDM.md
          - ModelSamplingDiscrete: md/Comfy/ModelSamplingDiscrete.md
          - ModelSamplingStableCascade: md/Comfy/ModelSamplingStableCascade.md
          - PatchModelAddDownscale: md/Comfy/PatchModelAddDownscale.md
          - PerpNeg: md/Comfy/PerpNeg.md
          - PhotoMakerEncode: md/Comfy/PhotoMakerEncode.md
          - PhotoMakerLoader: md/Comfy/PhotoMakerLoader.md
          - PolyexponentialScheduler: md/Comfy/PolyexponentialScheduler.md
          - PorterDuffImageComposite: md/Comfy/PorterDuffImageComposite.md
          - PreviewImage: md/Comfy/PreviewImage.md
          - RebatchImages: md/Comfy/RebatchImages.md
          - RebatchLatents: md/Comfy/RebatchLatents.md
          - RepeatImageBatch: md/Comfy/RepeatImageBatch.md
          - RepeatLatentBatch: md/Comfy/RepeatLatentBatch.md
          - RescaleCFG: md/Comfy/RescaleCFG.md
          - SDTurboScheduler: md/Comfy/SDTurboScheduler.md
          - SD_4XUpscale_Conditioning: md/Comfy/SD_4XUpscale_Conditioning.md
          - SVD_img2vid_Conditioning: md/Comfy/SVD_img2vid_Conditioning.md
          - SamplerCustom: md/Comfy/SamplerCustom.md
          - SamplerDPMPP_2M_SDE: md/Comfy/SamplerDPMPP_2M_SDE.md
          - SamplerDPMPP_SDE: md/Comfy/SamplerDPMPP_SDE.md
          - SaveAnimatedPNG: md/Comfy/SaveAnimatedPNG.md
          - SaveAnimatedWEBP: md/Comfy/SaveAnimatedWEBP.md
          - SaveImage: md/Comfy/SaveImage.md
          - SaveLatent: md/Comfy/SaveLatent.md
          - SelfAttentionGuidance: md/Comfy/SelfAttentionGuidance.md
          - SetLatentNoiseMask: md/Comfy/SetLatentNoiseMask.md
          - SolidMask: md/Comfy/SolidMask.md
          - SplitImageWithAlpha: md/Comfy/SplitImageWithAlpha.md
          - SplitSigmas: md/Comfy/SplitSigmas.md
          - StableCascade_EmptyLatentImage: md/Comfy/StableCascade_EmptyLatentImage.md
          - StableCascade_StageB_Conditioning: md/Comfy/StableCascade_StageB_Conditioning.md
          - StableCascade_StageC_VAEEncode: md/Comfy/StableCascade_StageC_VAEEncode.md
          - StableZero123_Conditioning: md/Comfy/StableZero123_Conditioning.md
          - StableZero123_Conditioning_Batched: md/Comfy/StableZero123_Conditioning_Batched.md
          - StyleModelApply: md/Comfy/StyleModelApply.md
          - StyleModelLoader: md/Comfy/StyleModelLoader.md
          - TomePatchModel: md/Comfy/TomePatchModel.md
          - UNETLoader: md/Comfy/UNETLoader.md
          - UpscaleModelLoader: md/Comfy/UpscaleModelLoader.md
          - VAEDecode: md/Comfy/VAEDecode.md
          - VAEDecodeTiled: md/Comfy/VAEDecodeTiled.md
          - VAEEncode: md/Comfy/VAEEncode.md
          - VAEEncodeForInpaint: md/Comfy/VAEEncodeForInpaint.md
          - VAEEncodeTiled: md/Comfy/VAEEncodeTiled.md
          - VAELoader: md/Comfy/VAELoader.md
          - VAESave: md/Comfy/VAESave.md
          - VPScheduler: md/Comfy/VPScheduler.md
          - VideoLinearCFGGuidance: md/Comfy/VideoLinearCFGGuidance.md
          - unCLIPCheckpointLoader: md/Comfy/unCLIPCheckpointLoader.md
          - unCLIPConditioning: md/Comfy/unCLIPConditioning.md
      - ComfyMath:
          - CM_BoolBinaryOperation: md/ComfyMath/CM_BoolBinaryOperation.md
          - CM_BoolToInt: md/ComfyMath/CM_BoolToInt.md
          - CM_BoolUnaryOperation: md/ComfyMath/CM_BoolUnaryOperation.md
          - CM_BreakoutVec2: md/ComfyMath/CM_BreakoutVec2.md
          - CM_BreakoutVec3: md/ComfyMath/CM_BreakoutVec3.md
          - CM_BreakoutVec4: md/ComfyMath/CM_BreakoutVec4.md
          - CM_ComposeVec2: md/ComfyMath/CM_ComposeVec2.md
          - CM_ComposeVec3: md/ComfyMath/CM_ComposeVec3.md
          - CM_ComposeVec4: md/ComfyMath/CM_ComposeVec4.md
          - CM_FloatBinaryCondition: md/ComfyMath/CM_FloatBinaryCondition.md
          - CM_FloatBinaryOperation: md/ComfyMath/CM_FloatBinaryOperation.md
          - CM_FloatToInt: md/ComfyMath/CM_FloatToInt.md
          - CM_FloatToNumber: md/ComfyMath/CM_FloatToNumber.md
          - CM_FloatUnaryCondition: md/ComfyMath/CM_FloatUnaryCondition.md
          - CM_FloatUnaryOperation: md/ComfyMath/CM_FloatUnaryOperation.md
          - CM_IntBinaryCondition: md/ComfyMath/CM_IntBinaryCondition.md
          - CM_IntBinaryOperation: md/ComfyMath/CM_IntBinaryOperation.md
          - CM_IntToBool: md/ComfyMath/CM_IntToBool.md
          - CM_IntToFloat: md/ComfyMath/CM_IntToFloat.md
          - CM_IntToNumber: md/ComfyMath/CM_IntToNumber.md
          - CM_IntUnaryCondition: md/ComfyMath/CM_IntUnaryCondition.md
          - CM_IntUnaryOperation: md/ComfyMath/CM_IntUnaryOperation.md
          - CM_NearestSDXLResolution: md/ComfyMath/CM_NearestSDXLResolution.md
          - CM_NumberBinaryCondition: md/ComfyMath/CM_NumberBinaryCondition.md
          - CM_NumberBinaryOperation: md/ComfyMath/CM_NumberBinaryOperation.md
          - CM_NumberToFloat: md/ComfyMath/CM_NumberToFloat.md
          - CM_NumberToInt: md/ComfyMath/CM_NumberToInt.md
          - CM_NumberUnaryCondition: md/ComfyMath/CM_NumberUnaryCondition.md
          - CM_NumberUnaryOperation: md/ComfyMath/CM_NumberUnaryOperation.md
          - CM_SDXLResolution: md/ComfyMath/CM_SDXLResolution.md
          - CM_Vec2BinaryCondition: md/ComfyMath/CM_Vec2BinaryCondition.md
          - CM_Vec2BinaryOperation: md/ComfyMath/CM_Vec2BinaryOperation.md
          - CM_Vec2ScalarOperation: md/ComfyMath/CM_Vec2ScalarOperation.md
          - CM_Vec2ToScalarBinaryOperation: md/ComfyMath/CM_Vec2ToScalarBinaryOperation.md
          - CM_Vec2ToScalarUnaryOperation: md/ComfyMath/CM_Vec2ToScalarUnaryOperation.md
          - CM_Vec2UnaryCondition: md/ComfyMath/CM_Vec2UnaryCondition.md
          - CM_Vec2UnaryOperation: md/ComfyMath/CM_Vec2UnaryOperation.md
          - CM_Vec3BinaryCondition: md/ComfyMath/CM_Vec3BinaryCondition.md
          - CM_Vec3BinaryOperation: md/ComfyMath/CM_Vec3BinaryOperation.md
          - CM_Vec3ScalarOperation: md/ComfyMath/CM_Vec3ScalarOperation.md
          - CM_Vec3ToScalarBinaryOperation: md/ComfyMath/CM_Vec3ToScalarBinaryOperation.md
          - CM_Vec3ToScalarUnaryOperation: md/ComfyMath/CM_Vec3ToScalarUnaryOperation.md
          - CM_Vec3UnaryCondition: md/ComfyMath/CM_Vec3UnaryCondition.md
          - CM_Vec3UnaryOperation: md/ComfyMath/CM_Vec3UnaryOperation.md
          - CM_Vec4BinaryCondition: md/ComfyMath/CM_Vec4BinaryCondition.md
          - CM_Vec4BinaryOperation: md/ComfyMath/CM_Vec4BinaryOperation.md
          - CM_Vec4ScalarOperation: md/ComfyMath/CM_Vec4ScalarOperation.md
          - CM_Vec4ToScalarBinaryOperation: md/ComfyMath/CM_Vec4ToScalarBinaryOperation.md
          - CM_Vec4ToScalarUnaryOperation: md/ComfyMath/CM_Vec4ToScalarUnaryOperation.md
          - CM_Vec4UnaryCondition: md/ComfyMath/CM_Vec4UnaryCondition.md
          - CM_Vec4UnaryOperation: md/ComfyMath/CM_Vec4UnaryOperation.md
      - ComfyUI_ADV_CLIP_emb:
          - BNK_AddCLIPSDXLParams: md/ComfyUI_ADV_CLIP_emb/BNK_AddCLIPSDXLParams.md
          - BNK_AddCLIPSDXLRParams: md/ComfyUI_ADV_CLIP_emb/BNK_AddCLIPSDXLRParams.md
          - BNK_CLIPTextEncodeAdvanced: md/ComfyUI_ADV_CLIP_emb/BNK_CLIPTextEncodeAdvanced.md
          - BNK_CLIPTextEncodeSDXLAdvanced: md/ComfyUI_ADV_CLIP_emb/BNK_CLIPTextEncodeSDXLAdvanced.md
      - ComfyUI_IPAdapter_plus:
          - IPAdapterApply: md/ComfyUI_IPAdapter_plus/IPAdapterApply.md
          - IPAdapterApplyEncoded: md/ComfyUI_IPAdapter_plus/IPAdapterApplyEncoded.md
          - IPAdapterApplyFaceID: md/ComfyUI_IPAdapter_plus/IPAdapterApplyFaceID.md
          - IPAdapterBatchEmbeds: md/ComfyUI_IPAdapter_plus/IPAdapterBatchEmbeds.md
          - IPAdapterEncoder: md/ComfyUI_IPAdapter_plus/IPAdapterEncoder.md
          - IPAdapterLoadEmbeds: md/ComfyUI_IPAdapter_plus/IPAdapterLoadEmbeds.md
          - IPAdapterModelLoader: md/ComfyUI_IPAdapter_plus/IPAdapterModelLoader.md
          - IPAdapterSaveEmbeds: md/ComfyUI_IPAdapter_plus/IPAdapterSaveEmbeds.md
          - InsightFaceLoader: md/ComfyUI_IPAdapter_plus/InsightFaceLoader.md
          - PrepImageForClipVision: md/ComfyUI_IPAdapter_plus/PrepImageForClipVision.md
          - PrepImageForInsightFace: md/ComfyUI_IPAdapter_plus/PrepImageForInsightFace.md
      - SavePNG:
          - PNG_Save: md/SavePNG/PNG_Save.md
      - WAS_Extras:
          - BLVAEEncode: md/WAS_Extras/BLVAEEncode.md
          - CLIPTextEncodeList: md/WAS_Extras/CLIPTextEncodeList.md
          - CLIPTextEncodeSequence2: md/WAS_Extras/CLIPTextEncodeSequence2.md
          - ConditioningBlend: md/WAS_Extras/ConditioningBlend.md
          - DebugInput: md/WAS_Extras/DebugInput.md
          - KSamplerSeq: md/WAS_Extras/KSamplerSeq.md
          - KSamplerSeq2: md/WAS_Extras/KSamplerSeq2.md
          - VAEEncodeForInpaint (WAS): md/WAS_Extras/VAEEncodeForInpaint (WAS).md
          - VividSharpen: md/WAS_Extras/VividSharpen.md
      - comfyui_segment_anything:
          - GroundingDinoModelLoader (segment anything): md/comfyui_segment_anything/GroundingDinoModelLoader
              (segment anything).md
          - GroundingDinoSAMSegment (segment anything): md/comfyui_segment_anything/GroundingDinoSAMSegment
              (segment anything).md
          - InvertMask (segment anything): md/comfyui_segment_anything/InvertMask
              (segment anything).md
          - IsMaskEmpty: md/comfyui_segment_anything/IsMaskEmpty.md
          - SAMModelLoader (segment anything): md/comfyui_segment_anything/SAMModelLoader
              (segment anything).md
      - llmnodes:
          - DocumentNode: md/llmnodes/DocumentNode.md
          - DocumentPack: md/llmnodes/DocumentPack.md
          - LoadOpenAIModel: md/llmnodes/LoadOpenAIModel.md
      - plaiflowplayer_blocks:
          - PlaiFlowPlayerAppFooter: md/plaiflowplayer_blocks/PlaiFlowPlayerAppFooter.md
          - PlaiFlowPlayerAppInfo: md/plaiflowplayer_blocks/PlaiFlowPlayerAppInfo.md
          - PlaiFlowPlayerInput: md/plaiflowplayer_blocks/PlaiFlowPlayerInput.md
          - PlaiFlowPlayerModelList: md/plaiflowplayer_blocks/PlaiFlowPlayerModelList.md
          - PlaiFlowPlayerOutput: md/plaiflowplayer_blocks/PlaiFlowPlayerOutput.md
          - PlaiFlowPlayerSAMSplit: md/plaiflowplayer_blocks/PlaiFlowPlayerSAMSplit.md
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - toc:
      permalink: true
  - pymdownx.keys
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/get-salt-AI
      name: Salt AI Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/saltai
      name: Salt AI Discord
